# -*- coding: utf-8 -*-
"""RegEx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tBOXp3QX2bntB-ZBrFpq_ixHzlrL9jD
"""

#import regular expression module
import re

#create data and pattern
pattern = 'python'
data='python is fast and easy to use. I have keen interest in python'

#apply search function to find first occurance of pattern
m = re.search(pattern,data)
print(m)

#start index
print(m.start())

#end index
print(m.end())

#other programs related to different patterns and first occurance of python
p1 = r'python'
d1 = 'python is fast and easy to use. I have keen interest in python'
m1 = re.search(p1,d1)
print(m1)

#find first occurance of digit from data
p2 = r'[0-9]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance of lowercase character from data
p2 = r'[a-z]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance of uppercase character from data
p2 = r'[A-Z]'
d2 = 'python3.13 is Fast and easy to Use. I have Keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance of digit and uppercase character from data
p2 = r'[0-9A-Z]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance of digit and uppercase character from data
p2 = r'[A-Z0-9]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance of digit and lowercase character from data
p2 = r'[a-z0-9]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

#find first occurance excluding these characters or digits
p2 = r'[^p3f]'
d2 = 'python3.13 is fast and easy to use. I have keen interest in python'
m3 = re.search(p2,d2)
print(m3)

